### ISSUE TITLE
PowerShell tab completion

### ISSUE THREAD

**Issue by flcdrg** [mwallner/rocolatey#48]
Would like this.. so used to typing `choco out`<kbd>tab</kbd> 🙂

**Comment by mwallner** [comment]
https://dev.to/kbknapp/cli-shell-completions-in-rust-37g1

**Comment by mwallner** [comment]
![grafik](https://user-images.githubusercontent.com/5354972/125855813-b7d15d11-9cfa-4337-934d-0b3892b91d1a.png)
yay :smile:

**Comment by mwallner** [comment]
it works, but I don't like having an extra parameter for each supported shell.
I'll probably just add _one_ toplevel command with further subcommands for each shell, something like

```
roco shell-completion -bash
roco shell-completion -pwsh
```
etc.

**Comment by mwallner** [comment]
implemented in GH-54 / ditched the idea with an extra subcommand - moved tab completion file to compile time (much cleaner imo)
