### ISSUE TITLE
Plans to add upgrade support?

### ISSUE THREAD

**Issue by asheroto** [mwallner/rocolatey#68]
Hey, thanks for building this!

Do you plan to add support for upgrading packages?  `roco upgrade all` etc?

**Comment by mwallner** [comment]
1.5 years later, I still think adding "upgrade support" to rocolatey is not the way to go - simply upgrading everything that can be upgraded without revisiting the list of update candidates can go very wrong and that's not something I want people to do by accident.

On the other hand, I'm guessing a `-l` switch for the outdated command, simply outputting a list of outdated commands really could come in handy - it would enable something like @asheroto suggested:

`choco upgrade (roco outdated -l)`
