### ISSUE TITLE
Make --ignore-pinned default

### ISSUE THREAD

**Issue by flcdrg** [mwallner/rocolatey#79]
Or make a way to configure it as the default.

Personally I always run `roco outdated --ignore-pinned` so would be nice to not have to type the extra bits 😄

**Comment by mwallner** [comment]
I changed my mind, `--ignore-pinned` and `--ignore-unfound` will be enabled by default in version 0.7, if the user desires to "re-enable" the switches there is a compatibility option called `--choco-compat`.
(see e8df749e61a903626e95dae734f54a1066a1b269)
